[package]
name = "libffi"
version = "3.2.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
description = "Rust bindings for libffi"
repository = "https://github.com/tov/libffi-rs"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["ffi", "libffi", "closure", "c"]
categories = ["development-tools::ffi"]
edition = "2018"

[dependencies]
libffi-sys = { path = "../libffi-sys-rs", version = "^2.3" }
libc = "0.2.65"

[features]
complex = []
system = ["libffi-sys/system"]
no_std = []

[package.metadata.docs.rs]
features = ["system"]
